export type Lang = "en" | "zh";

export type DemoStep = {
  title: { en: string; zh: string };
  detail: { en: string; zh: string };
  tx: `0x${string}`;
};

export const DEMO_STEPS: DemoStep[] = [
  {
    title: { en: "Deploy the plan", zh: "部署计划" },
    detail: { en: "Immutable escrow: market, executor, verifier, and deadlines frozen.", zh: "不可变托管：市场、执行者、验收者和期限一次性冻结。" },
    tx: "0xd431002eab001709a6cbbceb49ce534371f73394c077e2ed16ff8673425cd5a9",
  },
  {
    title: { en: "Mint a complete set", zh: "铸造完整份额" },
    detail: { en: "150 tUSDC → 150 Up + 150 Down via DreamDEX mintSet.", zh: "150 tUSDC 经 DreamDEX mintSet 变成 150 Up + 150 Down。" },
    tx: "0xd2cd66550abe5befe127d1aee0553281989749e92cb3c5cdfa8aa3ca42071f0d",
  },
  {
    title: { en: "Alice funds Up", zh: "Alice 看涨出资" },
    detail: { en: "100 Up deposited into BASE_UP. She does not have to concede.", zh: "100 份 Up 进入 BASE_UP。她不必认输。" },
    tx: "0x0ff65aaaed82455d748b863e23f25dffb8b83d6f554f3d09b57fd5865afe2848",
  },
  {
    title: { en: "Bob funds Down", zh: "Bob 看跌出资" },
    detail: { en: "100 Down deposited into BASE_DOWN. Complementary shares now match.", zh: "100 份 Down 进入 BASE_DOWN。互补份额凑齐。" },
    tx: "0x19410c46748379dced0223d4115a054e2dfd38ae45995ccbb2b81fb210fa5440",
  },
  {
    title: { en: "Merge → 100 tUSDC budget", zh: "合并 → 100 tUSDC 预算" },
    detail: { en: "1 Up + 1 Down = 1 collateral. Base task funded before settlement.", zh: "1 Up + 1 Down = 1 抵押品。基础任务在结算前就有钱。" },
    tx: "0x454119d783de1b77594dbb7ecdb1d67a621899e59232663cd8819f8de856ba0e",
  },
  {
    title: { en: "Market resolved Down", zh: "市场结算为 Down" },
    detail: { en: "Somnia Reactivity auto-called sync. Bonus skipped — Up condition failed.", zh: "Somnia Reactivity 自动推进。Up 条件未满足，追加任务跳过。" },
    tx: "0x232df62a9d3226aea7fbf0a83ab5fcb247b3c4ec1ebc284678138fbf817db73b",
  },
];

export const copy = {
  en: {
    title: "COMMON GROUND — Conditional public action",
    brand: "COMMON GROUND",
    connect: "Connect wallet",
    signIn: "Sign in",
    signed: "Signed",
    live: "LIVE",
    poll: "POLL",
    faucetTusdc: "Get tUSDC",
    faucetStt: "Get STT ↗",
    onboard1: "Read the live proof",
    onboard2: "Pick a side",
    onboard3: "One click funds a real task",
    hero1: "You don't have to agree",
    hero2: "to make something happen.",
    subBefore: "1 Up + 1 Down = 1 collateral",
    subAfter:
      ". Two people who disagree jointly fund a real task. The market only decides whether a second budget is released.",
    loading: "Reading on-chain state…",
    chipUp: "Up position",
    chipDown: "Down position",
    chipMerge: "merge",
    plans: "Plans",
    create: "New plan",
    creating: "Creating…",
    demoPlan: "Community Maintenance Check",
    planState: "Plan state",
    baseBudget: "Base budget",
    bonusBudget: "Bonus budget",
    contributors: "Contributors",
    planLabels: ["Pending", "Base active", "Completed", "Unfunded", "Refundable"],
    taskLabels: ["Waiting", "Ready", "Running", "Delivered", "Accepted", "Rejected", "Expired", "Skipped"],
    unconditional: "UNCONDITIONAL",
    conditional: "CONDITIONAL",
    baseTitle: "Base task · funded either way",
    baseBody:
      "Complementary Up and Down shares merge into a deterministic budget. Direction does not have to agree.",
    bonusTitle: "Bonus task · only after settlement",
    bonusBody:
      "Released only if the market resolves Up. Otherwise it is skipped and leftover shares refund.",
    evidence: "Delivery evidence",
    reason: "Verifier reason",
    budget: "Budget",
    fundUp: "Fund Up ↑",
    fundDown: "Fund Down ↓",
    fundBonus: "Add 50 tUSDC",
    campaign: "Plan contract",
    mergeBtn: "Merge base budget",
    merging: "Merging…",
    settled: "Market settled",
    settledNote:
      "This demo market already resolved Down. Funding a new side here will fail (TradingNotActive). Use the proof below — or deploy a fresh plan on a live Trading market.",
    judgeKicker: "For judges · 60-second read",
    judgeLine:
      "Somnia Shannon testnet · DreamDEX Event Contracts (mintSet / merge / redeem) · Somnia Reactivity auto-trigger · no off-chain keeper",
    storyTitle: "Completed live run",
    storyLead:
      "Alice was Up. Bob was Down. They jointly funded a 100 tUSDC maintenance check before the market settled. The market resolved Down, so the Up-conditioned bonus was correctly skipped.",
    storyResult: "Final on-chain state",
    resultBase: "100 tUSDC base — deterministic, from merged shares",
    resultBonus: "0 bonus · bonus task Skipped",
    openTx: "tx",
    openAddr: "explorer",
    proofTitle: "On-chain proof",
    docs: "Docs",
    github: "GitHub",
    switchLang: "中文",
  },
  zh: {
    title: "COMMON GROUND — 条件式公共行动",
    brand: "COMMON GROUND",
    connect: "连接钱包",
    signIn: "签名验证",
    signed: "已验证",
    live: "LIVE",
    poll: "POLL",
    faucetTusdc: "领测试 tUSDC",
    faucetStt: "领 STT ↗",
    onboard1: "先看链上证据",
    onboard2: "选一个立场",
    onboard3: "一键资助真实任务",
    hero1: "不必对未来达成一致，",
    hero2: "也能共同完成一件事。",
    subBefore: "1 Up + 1 Down = 1 抵押品",
    subAfter: "。两个观点相反的人一起出钱做一件真事；市场涨跌只决定第二笔钱发不发。",
    loading: "正在读取链上状态…",
    chipUp: "看涨仓位",
    chipDown: "看跌仓位",
    chipMerge: "合并",
    plans: "计划列表",
    create: "+ 创建计划",
    creating: "创建中…",
    demoPlan: "社区维护检查",
    planState: "计划状态",
    baseBudget: "基础预算",
    bonusBudget: "追加预算",
    contributors: "贡献者",
    planLabels: ["待启动", "基础已激活", "已完成", "募资失败", "可退款"],
    taskLabels: ["等待", "就绪", "执行中", "已交付", "已验收", "已驳回", "已过期", "已跳过"],
    unconditional: "无条件",
    conditional: "有条件",
    baseTitle: "基础任务 · 无论如何都做",
    baseBody: "选一个立场，另一方补上互补份额，合并成确定性预算。方向不同也能一起出资。",
    bonusTitle: "追加任务 · 结算后才触发",
    bonusBody: "仅当市场结果为 Up 时才追加边界 / 异常检查。条件不满足即跳过。",
    evidence: "交付证据",
    reason: "验收理由",
    budget: "预算",
    fundUp: "看涨 ↑ 资助",
    fundDown: "看跌 ↓ 资助",
    fundBonus: "追加 50 tUSDC",
    campaign: "计划合约",
    mergeBtn: "合并基础预算",
    merging: "合并中…",
    settled: "市场已结算",
    settledNote:
      "这条演示市场已经结算为 Down。再点资助会失败（TradingNotActive）。请先看下方证据；要现场操作，请换一个仍在 Trading 的市场部署新计划。",
    judgeKicker: "给评委 · 60 秒读完",
    judgeLine:
      "Somnia Shannon 测试网 · DreamDEX Event Contracts（mintSet / merge / redeem）· Somnia Reactivity 自动触发 · 无链下 keeper",
    storyTitle: "已完成的链上演示",
    storyLead:
      "Alice 看涨，Bob 看跌。他们在结算前共同凑出 100 tUSDC 维护检查预算。市场结算为 Down，Up 条件的追加任务被正确跳过。",
    storyResult: "最终链上状态",
    resultBase: "基础预算 100 tUSDC — 由互补份额合并，方向无关",
    resultBonus: "追加预算 0 · 追加任务已跳过",
    openTx: "交易",
    openAddr: "浏览器",
    proofTitle: "链上证据",
    docs: "文档",
    github: "GitHub",
    switchLang: "EN",
  },
} as const;
